title: Simple Sheet
description: A collection of easy to use Google Sheet tools for pulling asset prices of stocks, crypto, and metals. And more!
theme: just-the-docs
url: "https://simplesheet.github.io"
logo: "/assets/images/simple-sheet-logo.png"
color_scheme: custom

plugins:
  - jekyll-default-layout