title: Simple Sheet
description: A collection of easy to use open-source Google Sheet tools.
theme: just-the-docs
url: "https://simplesheet.github.io"
logo: "/assets/images/website-banner.png"
color_scheme: custom

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
    
plugins:
  - jekyll-default-layout